version: "3.8"

services:
  db:
    image: mysql:8
    restart: always
    network_mode: "host"
    volumes:
      - "/var/lib/mysql-docker/db:/var/lib/mysql"
      - "/usr/share/zoneinfo/America/New_York:/etc/localtime:ro"
    environment:
      MYSQL_ROOT_PASSWORD: "1jcZ%rZo86xmd&5x"
      MYSQL_PASSWORD: "t*dYvNhBH^m&IZGx"
      MYSQL_DATABASE: "dbhost"
      MYSQL_USER: "dbhost"
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
